In [1]:
import pandas as pd
import numpy as np

cars_df = pd.read_csv('used_cars_data.csv')

C:\Users\Checkout\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (11) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [2]:
cars_df.head()

,vin,back_legroom,bed,bed_height,bed_length,body_type,cabin,city,city_fuel_economy,combine_fuel_economy,...,transmission,transmission_display,trimId,trim_name,vehicle_damage_category,wheel_system,wheel_system_display,wheelbase,width,year
0,ZACNJABB5KPJ92081,35.1 in,NaN,NaN,NaN,SUV / Crossover,NaN,Bayamon,NaN,NaN,...,A,9-Speed Automatic Overdrive,t83804,Latitude FWD,NaN,FWD,Front-Wheel Drive,101.2 in,79.6 in,2019
1,SALCJ2FX1LH858117,38.1 in,NaN,NaN,NaN,SUV / Crossover,NaN,San Juan,NaN,NaN,...,A,9-Speed Automatic Overdrive,t86759,S AWD,NaN,AWD,All-Wheel Drive,107.9 in,85.6 in,2020
2,JF1VA2M67G9829723,35.4 in,NaN,NaN,NaN,Sedan,NaN,Guaynabo,17.0,NaN,...,M,6-Speed Manual,t58994,Base,NaN,AWD,All-Wheel Drive,104.3 in,78.9 in,2016
3,SALRR2RV0L2433391,37.6 in,NaN,NaN,NaN,SUV / Crossover,NaN,San Juan,NaN,NaN,...,A,8-Speed Automatic Overdrive,t86074,V6 HSE AWD,NaN,AWD,All-Wheel Drive,115 in,87.4 in,2020
4,SALCJ2FXXLH862327,38.1 in,NaN,NaN,NaN,SUV / Crossover,NaN,San Juan,NaN,NaN,...,A,9-Speed Automatic Overdrive,t86759,S AWD,NaN,AWD,All-Wheel Drive,107.9 in,85.6 in,2020

In [3]:
cars_df.tail()

,vin,back_legroom,bed,bed_height,bed_length,body_type,cabin,city,city_fuel_economy,combine_fuel_economy,...,transmission,transmission_display,trimId,trim_name,vehicle_damage_category,wheel_system,wheel_system_display,wheelbase,width,year
3000035,2GNAXJEV0J6261526,39.7 in,NaN,NaN,NaN,SUV / Crossover,NaN,Fairfield,26.0,NaN,...,A,Automatic,t72936,1.5T LT FWD,NaN,FWD,Front-Wheel Drive,107.3 in,72.6 in,2018
3000036,1GNERFKW0LJ225508,38.4 in,NaN,NaN,NaN,SUV / Crossover,NaN,Vallejo,18.0,NaN,...,A,Automatic,t85763,LS FWD,NaN,FWD,Front-Wheel Drive,120.9 in,78.6 in,2020
3000037,3FA6P0HD3GR134062,38.3 in,NaN,NaN,NaN,Sedan,NaN,Napa,NaN,NaN,...,A,6-Speed Automatic Overdrive,t57569,SE,NaN,FWD,Front-Wheel Drive,112.2 in,83.5 in,2016
3000038,SAJAJ4BNXHA968809,35 in,NaN,NaN,NaN,Sedan,NaN,Fairfield,30.0,NaN,...,A,Automatic,t65977,20d Premium AWD,NaN,AWD,All-Wheel Drive,111.6 in,81.7 in,2017
3000039,JN8AT2MT1HW400805,37.9 in,NaN,NaN,NaN,SUV / Crossover,NaN,Napa,26.0,NaN,...,A,Automatic,t76529,2017.5 SV FWD,NaN,FWD,Front-Wheel Drive,106.5 in,72.4 in,2017

In [4]:
cars_df.isna().sum()

vin                           0
back_legroom             159269
bed                     2980472
bed_height              2570942
bed_length              2570942
                         ...
wheel_system             146732
wheel_system_display     146732
wheelbase                159269
width                    159269
year                          0
Length: 66, dtype: int64

In [5]:
cars_df.dropna()

Empty DataFrame
Columns: [vin, back_legroom, bed, bed_height, bed_length, body_type, cabin, city, city_fuel_economy, combine_fuel_economy, daysonmarket, dealer_zip, description, engine_cylinders, engine_displacement, engine_type, exterior_color, fleet, frame_damaged, franchise_dealer, franchise_make, front_legroom, fuel_tank_volume, fuel_type, has_accidents, height, highway_fuel_economy, horsepower, interior_color, isCab, is_certified, is_cpo, is_new, is_oemcpo, latitude, length, listed_date, listing_color, listing_id, longitude, main_picture_url, major_options, make_name, maximum_seating, mileage, model_name, owner_count, power, price, salvage, savings_amount, seller_rating, sp_id, sp_name, theft_title, torque, transmission, transmission_display, trimId, trim_name, vehicle_damage_category, wheel_system, wheel_system_display, wheelbase, width, year]
Index: []

[0 rows x 66 columns]

In [6]:
#Dropping columns with many null values
cars_df.drop(['cabin','bed','bed_height','bed_length','combine_fuel_economy','vehicle_damage_category'], inplace=True, axis=1)

In [7]:
cars_df.columns

Index(['vin', 'back_legroom', 'body_type', 'city', 'city_fuel_economy',
       'daysonmarket', 'dealer_zip', 'description', 'engine_cylinders',
       'engine_displacement', 'engine_type', 'exterior_color', 'fleet',
       'frame_damaged', 'franchise_dealer', 'franchise_make', 'front_legroom',
       'fuel_tank_volume', 'fuel_type', 'has_accidents', 'height',
       'highway_fuel_economy', 'horsepower', 'interior_color', 'isCab',
       'is_certified', 'is_cpo', 'is_new', 'is_oemcpo', 'latitude', 'length',
       'listed_date', 'listing_color', 'listing_id', 'longitude',
       'main_picture_url', 'major_options', 'make_name', 'maximum_seating',
       'mileage', 'model_name', 'owner_count', 'power', 'price', 'salvage',
       'savings_amount', 'seller_rating', 'sp_id', 'sp_name', 'theft_title',
       'torque', 'transmission', 'transmission_display', 'trimId', 'trim_name',
       'wheel_system', 'wheel_system_display', 'wheelbase', 'width', 'year'],
      dtype='object')

In [8]:
# check for duplicates
cars_df['vin'].duplicated().sum()

40

In [12]:
cars_df.drop_duplicates(subset=['vin'])

,vin,back_legroom,body_type,city,city_fuel_economy,daysonmarket,dealer_zip,description,engine_cylinders,engine_displacement,...,torque,transmission,transmission_display,trimId,trim_name,wheel_system,wheel_system_display,wheelbase,width,year
0,ZACNJABB5KPJ92081,35.1 in,SUV / Crossover,Bayamon,NaN,522,960,[!@@Additional Info@@!]Engine: 2.4L I4 ZERO EV...,I4,1300.0,...,"200 lb-ft @ 1,750 RPM",A,9-Speed Automatic Overdrive,t83804,Latitude FWD,FWD,Front-Wheel Drive,101.2 in,79.6 in,2019
1,SALCJ2FX1LH858117,38.1 in,SUV / Crossover,San Juan,NaN,207,922,"[!@@Additional Info@@!]Keyless Entry,Ebony Mor...",I4,2000.0,...,"269 lb-ft @ 1,400 RPM",A,9-Speed Automatic Overdrive,t86759,S AWD,AWD,All-Wheel Drive,107.9 in,85.6 in,2020
2,JF1VA2M67G9829723,35.4 in,Sedan,Guaynabo,17.0,1233,969,NaN,H4,2500.0,...,"290 lb-ft @ 4,000 RPM",M,6-Speed Manual,t58994,Base,AWD,All-Wheel Drive,104.3 in,78.9 in,2016
3,SALRR2RV0L2433391,37.6 in,SUV / Crossover,San Juan,NaN,196,922,"[!@@Additional Info@@!]Fog Lights,7 Seat Packa...",V6,3000.0,...,"332 lb-ft @ 3,500 RPM",A,8-Speed Automatic Overdrive,t86074,V6 HSE AWD,AWD,All-Wheel Drive,115 in,87.4 in,2020
4,SALCJ2FXXLH862327,38.1 in,SUV / Crossover,San Juan,NaN,137,922,"[!@@Additional Info@@!]Keyless Entry,Ebony Mor...",I4,2000.0,...,"269 lb-ft @ 1,400 RPM",A,9-Speed Automatic Overdrive,t86759,S AWD,AWD,All-Wheel Drive,107.9 in,85.6 in,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3000035,2GNAXJEV0J6261526,39.7 in,SUV / Crossover,Fairfield,26.0,16,94533,CarMax Curbside is now available at select sto...,I4,1500.0,...,NaN,A,Automatic,t72936,1.5T LT FWD,FWD,Front-Wheel Drive,107.3 in,72.6 in,2018
3000036,1GNERFKW0LJ225508,38.4 in,SUV / Crossover,Vallejo,18.0,171,94591,Prices do not include government fees and taxe...,V6,3600.0,...,"266 lb-ft @ 2,800 RPM",A,Automatic,t85763,LS FWD,FWD,Front-Wheel Drive,120.9 in,78.6 in,2020
3000037,3FA6P0HD3GR134062,38.3 in,Sedan,Napa,NaN,91,94559,Introducing the 2016 Ford Fusion! Offering an ...,NaN,2000.0,...,"270 lb-ft @ 1,750 RPM",A,6-Speed Automatic Overdrive,t57569,SE,FWD,Front-Wheel Drive,112.2 in,83.5 in,2016
3000038,SAJAJ4BNXHA968809,35 in,Sedan,Fairfield,30.0,11,94533,CarMax Curbside is now available at select sto...,I4 Diesel,2000.0,...,"318 lb-ft @ 1,750 RPM",A,Automatic,t65977,20d Premium AWD,AWD,All-Wheel Drive,111.6 in,81.7 in,2017
3000039,JN8AT2MT1HW400805,37.9 in,SUV / Crossover,Napa,26.0,17,94559,"Here it is!! In these economic times, a super ...",I4,2500.0,...,"175 lb-ft @ 4,400 RPM",A,Automatic,t76529,2017.5 SV FWD,FWD,Front-Wheel Drive,106.5 in,72.4 in,2017

In [9]:
cars_df['body_type'].unique()

array(['SUV / Crossover', 'Sedan', 'Coupe', 'Hatchback', 'Pickup Truck',
       'Wagon', 'Minivan', 'Van', 'Convertible', nan], dtype=object)

In [10]:
cars_df[cars_df.duplicated(['vin'], keep=False)]

,vin,back_legroom,body_type,city,city_fuel_economy,daysonmarket,dealer_zip,description,engine_cylinders,engine_displacement,...,torque,transmission,transmission_display,trimId,trim_name,wheel_system,wheel_system_display,wheelbase,width,year
1000000,3FA6P0H79GR344482,38.3 in,Sedan,Washington Court House,22.0,6,43160,NaN,I4,2000.0,...,"270 lb-ft @ 1,750 RPM",A,Automatic,t57569,SE,FWD,Front-Wheel Drive,112.2 in,83.5 in,2016
1000001,3TMCZ5AN4KM203273,32.6 in,Pickup Truck,Groveport,18.0,6,43125,"Click the Express button, Free home delivery o...",V6,3500.0,...,"265 lb-ft @ 4,600 RPM",A,6-Speed Automatic,t80343,SR V6 Double Cab 4WD,4WD,Four-Wheel Drive,127.4 in,74.4 in,2019
1000002,1FTEW1EP0HKC03244,43.6 in,Pickup Truck,Groveport,18.0,65,43125,"Click the Express button, Free home delivery o...",V6,3500.0,...,"470 lb-ft @ 2,500 RPM",A,6-Speed Automatic,t69641,XLT SuperCrew 4WD,4WD,Four-Wheel Drive,145 in,96.8 in,2017
1000003,3FADP4EJ0KM129514,31.2 in,Hatchback,Washington Court House,27.0,253,43160,[!@@Additional Info@@!]Backup CameraRear View ...,I4,1600.0,...,"112 lb-ft @ 5,000 RPM",A,Automatic,t82591,SE Hatchback FWD,FWD,Front-Wheel Drive,98 in,77.8 in,2019
1000004,1N6AD0EV6KN713209,33.6 in,Pickup Truck,Heath,15.0,32,43056,CARFAX One-Owner. Clean CARFAX. Certified. Gun...,V6,4000.0,...,"281 lb-ft @ 4,000 RPM",A,5-Speed Automatic,t83539,PRO-4X Crew Cab 4WD,4WD,Four-Wheel Drive,125.9 in,72.8 in,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2000055,1J8GN28K68W204434,38.8 in,SUV / Crossover,Deer Park,15.0,182,99006,2008 Jeep Liberty 4WD with the 3.7L V6 engine....,V6,3700.0,...,"235 lb-ft @ 4,000 RPM",A,Automatic,t32046,Sport 4WD,4WD,Four-Wheel Drive,106.1 in,72.3 in,2008
2000056,4S4BSACC8H3397705,38.1 in,Wagon,Bonners Ferry,25.0,51,83805,Summary: Clean little Subaru for back of marke...,H4,2500.0,...,"174 lb-ft @ 4,000 RPM",CVT,Continuously Variable Transmission,t68628,2.5i Premium,AWD,All-Wheel Drive,108.1 in,81.3 in,2017
2000057,JTEBU5JR5K5687002,32.9 in,SUV / Crossover,Airway Heights,17.0,20,99001,"CARFAX 1-Owner, GREAT MILES 15,000! SR5 Premiu...",V6,4000.0,...,"278 lb-ft @ 4,400 RPM",A,Automatic,t80268,SR5 Premium 4WD,4WD,Four-Wheel Drive,109.8 in,75.8 in,2019
2000058,1GYKPHRS0LZ102741,39.1 in,SUV / Crossover,Salt Lake City,17.0,432,84115,Sport Loaner AWD 9-Speed Automatic 3.6L V6 DI ...,V6,3600.0,...,"271 lb-ft @ 4,900 RPM",A,Automatic,t85155,Sport AWD,4WD,Four-Wheel Drive,112.7 in,77.3 in,2020
2000059,1G1ZE5E1XBF285533,37.6 in,Sedan,Deer Park,22.0,48,99006,We stock over 500 used vehicles all in one loc...,I4,2400.0,...,"251 lb-ft @ 3,200 RPM",A,Automatic,t37841,LTZ FWD,FWD,Front-Wheel Drive,112.3 in,70.3 in,2011

In [11]:
# checking an example for a duplicate
cars_df.loc[cars_df['vin'] == '3FA6P0H79GR344482']

,vin,back_legroom,body_type,city,city_fuel_economy,daysonmarket,dealer_zip,description,engine_cylinders,engine_displacement,...,torque,transmission,transmission_display,trimId,trim_name,wheel_system,wheel_system_display,wheelbase,width,year
1000000,3FA6P0H79GR344482,38.3 in,Sedan,Washington Court House,22.0,6,43160,NaN,I4,2000.0,...,"270 lb-ft @ 1,750 RPM",A,Automatic,t57569,SE,FWD,Front-Wheel Drive,112.2 in,83.5 in,2016
1000020,3FA6P0H79GR344482,38.3 in,Sedan,Washington Court House,22.0,6,43160,NaN,I4,2000.0,...,"270 lb-ft @ 1,750 RPM",A,Automatic,t57569,SE,FWD,Front-Wheel Drive,112.2 in,83.5 in,2016

In [13]:
cars_df.describe()

,city_fuel_economy,daysonmarket,engine_displacement,highway_fuel_economy,horsepower,is_certified,latitude,listing_id,longitude,mileage,owner_count,price,savings_amount,seller_rating,sp_id,year
count,2.508755e+06,3.000040e+06,2.827654e+06,2.508755e+06,2.827654e+06,0.0,3.000040e+06,3.000040e+06,3.000040e+06,2.855653e+06,1.483027e+06,3.000040e+06,3.000040e+06,2.959168e+06,2.999944e+06,3.000040e+06
mean,2.269325e+01,7.605973e+01,2.968488e+03,2.947337e+01,2.479957e+02,NaN,3.698414e+01,2.754987e+08,-9.064224e+01,3.114690e+04,1.532644e+00,2.993337e+04,5.509768e+02,4.270413e+00,2.335224e+05,2.017728e+03
std,8.807024e+00,1.088839e+02,1.348905e+03,7.769252e+00,9.046639e+01,NaN,4.996819e+00,8.894123e+06,1.390589e+01,7.458675e+04,9.202928e-01,1.956617e+04,1.079448e+03,5.133017e-01,1.323221e+05,4.178701e+00
min,7.000000e+00,0.000000e+00,7.000000e+02,1.000000e+01,5.500000e+01,NaN,1.834670e+01,1.994620e+07,-1.579280e+02,0.000000e+00,1.000000e+00,1.650000e+02,0.000000e+00,1.000000e+00,4.159300e+04,1.915000e+03
25%,1.800000e+01,1.400000e+01,2.000000e+03,2.500000e+01,1.750000e+02,NaN,3.350920e+01,2.745794e+08,-9.708820e+01,6.000000e+00,1.000000e+00,1.845100e+04,0.000000e+00,4.000000e+00,6.337500e+04,2.017000e+03
50%,2.100000e+01,3.500000e+01,2.500000e+03,2.900000e+01,2.440000e+02,NaN,3.784710e+01,2.785453e+08,-8.724950e+01,8.267000e+03,1.000000e+00,2.647700e+04,0.000000e+00,4.341463e+00,2.816270e+05,2.020000e+03
75%,2.600000e+01,8.200000e+01,3.600000e+03,3.300000e+01,3.000000e+02,NaN,4.100620e+01,2.804553e+08,-8.045490e+01,4.366200e+04,2.000000e+00,3.822000e+04,7.850000e+02,4.605263e+00,3.366140e+05,2.020000e+03
max,1.270000e+02,3.599000e+03,8.400000e+03,1.270000e+02,1.001000e+03,NaN,6.120310e+01,2.820222e+08,-6.607850e+01,9.999999e+07,1.900000e+01,3.299995e+06,1.474140e+05,5.000000e+00,4.409510e+05,2.021000e+03

In [14]:
# removing part of data(inches)
cars_df['front_legroom'] = cars_df['front_legroom'].map(lambda x: str(x)[:-3])
cars_df['back_legroom'] = cars_df['back_legroom'].map(lambda x: str(x)[:-3])
cars_df['height'] = cars_df['height'].map(lambda x: str(x)[:-3])
cars_df['width'] = cars_df['width'].map(lambda x: str(x)[:-3])
cars_df['wheelbase'] = cars_df['wheelbase'].map(lambda x: str(x)[:-3])

In [15]:
cars_df.loc[cars_df['back_legroom'] == '']

,vin,back_legroom,body_type,city,city_fuel_economy,daysonmarket,dealer_zip,description,engine_cylinders,engine_displacement,...,torque,transmission,transmission_display,trimId,trim_name,wheel_system,wheel_system_display,wheelbase,width,year
10,ZARBAAC41FM129303,,Coupe,Guaynabo,NaN,1252,969,"[!@@Additional Info@@!]2 DOOR,4-WHEEL ABS BRAK...",I4,1700.0,...,"258 lb-ft @ 4,250 RPM",A,6-Speed Automatic,t56834,Launch Edition Coupe RWD,RWD,Rear-Wheel Drive,93.7,73.5,2015
50,4S3GTAA67J3747545,,Hatchback,Bronx,NaN,21,10466,CERTIFIED CLEAN CARFAX!!! One Owner Vehicle - ...,NaN,NaN,...,NaN,CVT,Continuously Variable Transmission,t90895,2.0i Touring Wagon AWD,NaN,NaN,,,2018
94,WDC0G4KB1GF094747,,SUV / Crossover,Bronx,21.0,19,10466,CERTIFIED CLEAN CARFAX!!! One Owner Vehicle - ...,I4,2000.0,...,"273 lb-ft @ 1,300 RPM",A,9-Speed Automatic,t60813,GLC 300 4MATIC,AWD,All-Wheel Drive,113.1,82.5,2016
114,4JGED6EB1JA108710,,SUV / Crossover,Bronx,17.0,58,10466,CERTIFIED CLEAN CARFAX!!! One Owner Vehicle - ...,V6,3000.0,...,"384 lb-ft @ 2,000 RPM",A,9-Speed Automatic,t75587,GLE AMG 43 4MATIC Coupe,AWD,All-Wheel Drive,114.8,84.3,2018
162,WDDGF8BBXCR195380,,Sedan,Bronx,NaN,29,10466,CERTIFIED CLEAN CARFAX!!! Bluetooth - Alloy Wh...,V6,NaN,...,NaN,A,7-Speed Automatic,NaN,NaN,NaN,NaN,,,2012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2999974,1FTFW1ET8CFB42101,,Pickup Truck,Ukiah,NaN,17,95482,"[!@@Additional Info@@!]GVWR: 7,350 lbs Payload...",V6,NaN,...,NaN,A,6-Speed Automatic,NaN,NaN,NaN,NaN,,,2012
2999975,1FTEW1EG7GKD83935,,Pickup Truck,Ukiah,NaN,27,95482,"[!@@Additional Info@@!]Power steering,Rear ste...",V6,NaN,...,NaN,A,6-Speed Automatic,NaN,NaN,NaN,NaN,,,2016
2999992,1N4AL3AP7FN310236,,Sedan,Napa,NaN,17,94559,Discerning drivers will appreciate the 2015 Ni...,I4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,2015
3000006,JTDKN3DU3D5576361,,Hatchback,Fremont,NaN,286,94538,"Online cash only special: $11,678+ fees...List...",I4 Hybrid,NaN,...,NaN,CVT,Continuously Variable Transmission,NaN,NaN,NaN,NaN,,,2013
3000032,3N6CM0KNXLK704386,,Van,Napa,24.0,62,94559,Hurry and take advantage now!! A awesome vehic...,I4,2000.0,...,"139 lb-ft @ 4,800 RPM",CVT,Continuously Variable Transmission,t88980,S FWD,FWD,Front-Wheel Drive,115.2,68.1,2020

In [16]:
cars_df['front_legroom'] = cars_df['front_legroom'].replace('', np.nan, regex=True)
cars_df['back_legroom'] = cars_df['back_legroom'].replace('', np.nan, regex=True)
cars_df['height'] = cars_df['height'].replace('', np.nan, regex=True)
cars_df['width'] = cars_df['width'].replace('', np.nan, regex=True)
cars_df['wheelbase'] = cars_df['wheelbase'].replace('', np.nan, regex=True)

In [17]:
cars_df = cars_df.astype({'front_legroom': 'float64', 'back_legroom': 'float64', 'height': 'float64', 'width': 'float64', 
               'wheelbase': 'float64'})

In [19]:
cars_df.isna().sum()

vin                           0
back_legroom             242727
body_type                 13543
city                          0
city_fuel_economy        491285
daysonmarket                  0
dealer_zip                    0
description               77901
engine_cylinders         100581
engine_displacement      172386
engine_type              100581
exterior_color               26
fleet                   1426595
frame_damaged           1426595
franchise_dealer              0
franchise_make           572635
front_legroom            175457
fuel_tank_volume         159269
fuel_type                 82724
has_accidents           1426595
height                   159737
highway_fuel_economy     491285
horsepower               172386
interior_color              165
isCab                   1426595
is_certified            3000040
is_cpo                  2817142
is_new                        0
is_oemcpo               2864678
latitude                      0
length                   159269
listed_date                   0
listing_color                 0
listing_id                    0
longitude                     0
main_picture_url         369093
major_options            200048
make_name                     0
maximum_seating          159269
mileage                  144387
model_name                    0
owner_count             1517013
power                    481426
price                         0
salvage                 1426595
savings_amount                0
seller_rating             40872
sp_id                        96
sp_name                       0
theft_title             1426595
torque                   517793
transmission              64185
transmission_display      64185
trimId                   115827
trim_name                116294
wheel_system             146732
wheel_system_display     146732
wheelbase                159702
width                    159750
year                          0
dtype: int64

In [20]:
cars_df.dtypes

vin                      object
back_legroom            float64
body_type                object
city                     object
city_fuel_economy       float64
daysonmarket              int64
dealer_zip               object
description              object
engine_cylinders         object
engine_displacement     float64
engine_type              object
exterior_color           object
fleet                    object
frame_damaged            object
franchise_dealer           bool
franchise_make           object
front_legroom           float64
fuel_tank_volume         object
fuel_type                object
has_accidents            object
height                  float64
highway_fuel_economy    float64
horsepower              float64
interior_color           object
isCab                    object
is_certified            float64
is_cpo                   object
is_new                     bool
is_oemcpo                object
latitude                float64
length                   object
listed_date              object
listing_color            object
listing_id                int64
longitude               float64
main_picture_url         object
major_options            object
make_name                object
maximum_seating          object
mileage                 float64
model_name               object
owner_count             float64
power                    object
price                   float64
salvage                  object
savings_amount            int64
seller_rating           float64
sp_id                   float64
sp_name                  object
theft_title              object
torque                   object
transmission             object
transmission_display     object
trimId                   object
trim_name                object
wheel_system             object
wheel_system_display     object
wheelbase               float64
width                   float64
year                      int64
dtype: object

In [21]:
cars_df['interior_color']

0                             Black
1                     Black (Ebony)
2                              None
3          Gray (Ebony/Ebony/Ebony)
4                     Black (Ebony)
                     ...
3000035                       Black
3000036                   Jet Black
3000037                        None
3000038                       Cream
3000039                        None
Name: interior_color, Length: 3000040, dtype: object

In [22]:
# We are having many colors in white color only,replacing them to only white
white = cars_df[cars_df['interior_color'].str.contains("white", na=False)] # 776 rows
unique_white = white['interior_color'].unique()

"\narray(['white', 'Minwhite', 'Majestic white', 'Ibis white', 'pearl white',\n       'glacier white metallic', 'Carrara white',\n       'Glacier white metallic', 'Cortina white', 'Superwhite',\n       'Gold,white', 'Off-white', 'White crystal white pearl',\n       'Pure white', 'Diamond white', 'diamond white',\n       'Moonlight white pearl', 'Glacierwhite', 'Offwhite',\n       'crystal white', 'carrara white metallic',\n       'mineral white metallic', 'Pearl_white', 'Red and white',\n       'alpine white', 'vice white', 'clear white', 'glacier white',\n       'frozen white met', 'pure white', 'white pearl', 'oxford white.',\n       'bright white cle', 'oxford white',\n       'Glacier white metallic / Black roof',\n       'Glacier white metallic / Red roof', 'Pearl white', 'Ultrawhite',\n       'Natural white', 'white metallic tri coat', 'Off white',\n       '[white] Glacier', 'Fuji white', 'Alpine white', 'cirrcus white',\n       'desingo diamond white', 'Crystalwhitepearl', 'white silver',\n       'crystal white pearl metallic', 'crystal white metallic',\n       'Crystalwhite', 'white      Warranty', 'Bright white',\n       'Chalkwhite', 'Clear_white', 'Glacial_white', 'Snow_white_pear',\n       'Star_white_tri-Coa', 'Purewhite', 'Pure_white', 'Winter white',\n       'Sumitwhite'], dtype=object)\n"

In [23]:
cars_df['interior_color'] = cars_df['interior_color'].replace(unique_white, 'white',regex=True)

In [24]:
# Changing to particular color
blue = cars_df[cars_df['interior_color'].str.contains("Blue", na=False)]
unique_blue = blue['interior_color'].unique()
black = cars_df[cars_df['interior_color'].str.contains("Black", na=False)]
unique_black = black['interior_color'].unique()
yellow = cars_df[cars_df['interior_color'].str.contains("Yellow", na=False)]
unique_yellow = yellow['interior_color'].unique()
red = cars_df[cars_df['interior_color'].str.contains("Red", na=False)]
unique_red = red['interior_color'].unique()

In [ ]:
cars_df['interior_color'] = cars_df['interior_color'].replace(unique_blue, 'blue',regex=True)

In [ ]:
cars_df['interior_color'] = cars_df['interior_color'].replace(unique_black, 'black',regex=True)

In [ ]:
cars_df['interior_color'] = cars_df['interior_color'].replace(unique_yellow, 'yellow',regex=True)

In [ ]:
cars_df['interior_color'] = cars_df['interior_color'].replace(unique_red, 'red',regex=True)

In [ ]:
# GRAY, SILVER, TUNGSTEN, STONE, GRAPHITE, PEARL, METALLIC
gray = cars_df[cars_df['interior_color'].str.contains(["Grey", "Gray", "Silver", "Tungsten", "Stone", "Graphite", 
                                                       "Pearl", "Metallic"],
                                                      na=False)]
unique_gray = gray['interior_color'].unique()
cars_df['interior_color'] = cars_df['interior_color'].replace(unique_gray, 'gray',regex=True)

In [ ]:
cars_df['exterior_color'].unique()

In [ ]:
cars_df['exterior_color']=cars_df['exterior_color'].replace('None','Black')

In [ ]:
cars_df['exterior_color'].unique()

In [ ]:
###Black
Black_ext = cars_df[cars_df['exterior_color'].str.contains("Black", na=False)] # 776 rows
black_exterior = Black_ext['exterior_color'].unique()
cars_df['exterior_color'] = cars_df['exterior_color'].replace(black_exterior, 'black',regex=True)

In [ ]:
cars_df['exterior_color'].unique()

In [ ]:
cars_df['fuel_type'].unique()

In [ ]:
cars_df.to_csv('user_car_cleaned.csv', encoding='utf-8')